[package]
name = "abut"
version = "0.1.0"
edition = "2024"

license = "MIT OR Apache-2.0"
description = "memory stuff"

authors = ["James Hunt <jameshuntdevelopment@gmail.com>"]
repository = "https://github.com/jameshuntt/abut"

[dependencies]
